version: '3'

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: calendrier_management
    ports:
      - "3307:3307"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  calendrier-service:
    build:
      context: ./CalendrierService
    ports:
      - "8091:8091"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/calendrier_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SERVER_PORT: 8091
      SPRING_APPLICATION_NAME: CALENDRIER-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_JAKARTA_PERSISTENCE_JDBC_URL: jdbc:mysql://mysql:3307/calendrier_management?createDatabaseIfNotExist=true
    depends_on:
      - mysql

  categorie-service:
    build:
      context: ./CategorieService
    ports:
      - "8089:8089"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/Categorie_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SERVER_PORT: 8089
      SPRING_APPLICATION_NAME: CATEGORIE-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_JAKARTA_PERSISTENCE_JDBC_URL: jdbc:mysql://mysql:3307/Categorie_management?createDatabaseIfNotExist=true
    depends_on:
      - mysql

  contact-service:
    build:
      context: ./ContactService
    ports:
      - "8086:8086"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/Contact_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SERVER_PORT: 8086
      SPRING_APPLICATION_NAME: CONTACT-SERVICE
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_JAKARTA_PERSISTENCE_JDBC_URL: jdbc:mysql://mysql:3307/Contact_management?createDatabaseIfNotExist=true
    depends_on:
      - mysql

  utilisateur-service:
    build:
      context: ./UtilisateurService
    ports:
      - "8093:8093"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/users_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SERVER_PORT: 8093
      SPRING_APPLICATION_NAME: SERVICE-USER
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_JAKARTA_PERSISTENCE_JDBC_URL: jdbc:mysql://mysql:3307/users_management?createDatabaseIfNotExist=true
    depends_on:
      - mysql

volumes:
  mysql-data:
